// AUTO-GENERATED by tools/gen-version.mjs — do not edit by hand.
// Bump the version in package.json; this file is regenerated on every build.
export const VERSION = '1.2.0';
export const BUILD_DATE = '2026-08-03';
export const GIT_SHA = '45ce3bf+';
