// AUTO-GENERATED by tools/gen-version.mjs — do not edit by hand.
// Bump the version in package.json; this file is regenerated on every build.
export const VERSION = '1.1.1';
export const BUILD_DATE = '2026-08-01';
export const GIT_SHA = 'ea8383d+';
