/**
 * Stamp the app's version into `src/app/version.ts` from package.json, plus the
 * build date and the current git commit — so the running app can show exactly
 * which build it is. Runs automatically before every build (the `prebuild`
 * script); the generated file is committed so `ng serve` has it too.
 *
 *   node tools/gen-version.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';

const pkg = JSON.parse(readFileSync('package.json', 'utf8'));

const git = (cmd) => {
  try {
    return execSync(cmd, { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    return '';
  }
};

const sha = git('git rev-parse --short HEAD');
const dirty = git('git status --porcelain').length > 0;
const date = new Date().toISOString().slice(0, 10);

const contents = `// AUTO-GENERATED by tools/gen-version.mjs — do not edit by hand.
// Bump the version in package.json; this file is regenerated on every build.
export const VERSION = '${pkg.version}';
export const BUILD_DATE = '${date}';
export const GIT_SHA = '${sha}${dirty && sha ? '+' : ''}';
`;

writeFileSync('src/app/version.ts', contents);
console.log(
  `  version.ts → v${pkg.version} (${sha || 'no-git'}${dirty ? ', uncommitted' : ''}) ${date}`
);
